/**
 * GENERATED FILE - DO NOT EDIT
 * This file is automatically generated by the generate-token-types script.
 * Generated on: 2025-11-02T15:39:46.727Z
 */

import {
  AchievementToken,
  AchieveToken,
  AllowReuseToken,
  ArithmeticOperatorToken,
  AuthorToken,
  BooleanLiteralToken,
  CheckAchievementsToken,
  ChoiceOptionToken,
  ChoiceToken,
  CloseBraceToken,
  CloseParenthesisToken,
  CloseSquareBracketToken,
  CommentToken,
  ComparisonOperatorToken,
  CreateArrayToken,
  CreateTempArrayToken,
  CreateTempVariableToken,
  CreateVariableToken,
  DeleteArrayToken,
  DeleteVariableToken,
  DisableReuseToken,
  DollarToken,
  ElseIfToken,
  ElseToken,
  EndingToken,
  FakeChoiceToken,
  FinishToken,
  GameIdentifierToken,
  GenerateRandomToken,
  GoSubSceneToken,
  GoSubToken,
  GotoLabelToken,
  GotoRandomSceneToken,
  GotoSceneToken,
  HideReuseToken,
  IdentifierToken,
  IfToken,
  ImageToken,
  IndexerToken,
  InputNumberToken,
  InputTextToken,
  LabelToken,
  LineBreakToken,
  LinkToken,
  LogicalOperatorToken,
  MultiReplaceElseToken,
  NumberLiteralToken,
  OpenMultiReplaceToken,
  OpenParenthesisToken,
  OpenPrintCapitaliseAllToken,
  OpenPrintCapitaliseFirstToken,
  OpenPrintToken,
  OpenSquareBracketToken,
  PageBreakToken,
  ParametersToken,
  ProseToken,
  RestoreCheckpointToken,
  ReturnToken,
  SaveCheckpointToken,
  SceneEndToken,
  SceneListToken,
  SceneStartToken,
  SelectableIfToken,
  SetVariableToken,
  StatChartToken,
  StringLiteralToken,
  UnaryOperatorToken,
} from './';

/**
 * Union type of all possible token types.
 * This is automatically extracted from all token interfaces.
 */
export type TokenType =
  | AchievementToken['type']
  | AchieveToken['type']
  | AllowReuseToken['type']
  | ArithmeticOperatorToken['type']
  | AuthorToken['type']
  | BooleanLiteralToken['type']
  | CheckAchievementsToken['type']
  | ChoiceOptionToken['type']
  | ChoiceToken['type']
  | CloseBraceToken['type']
  | CloseParenthesisToken['type']
  | CloseSquareBracketToken['type']
  | CommentToken['type']
  | ComparisonOperatorToken['type']
  | CreateArrayToken['type']
  | CreateTempArrayToken['type']
  | CreateTempVariableToken['type']
  | CreateVariableToken['type']
  | DeleteArrayToken['type']
  | DeleteVariableToken['type']
  | DisableReuseToken['type']
  | DollarToken['type']
  | ElseIfToken['type']
  | ElseToken['type']
  | EndingToken['type']
  | FakeChoiceToken['type']
  | FinishToken['type']
  | GameIdentifierToken['type']
  | GenerateRandomToken['type']
  | GoSubSceneToken['type']
  | GoSubToken['type']
  | GotoLabelToken['type']
  | GotoRandomSceneToken['type']
  | GotoSceneToken['type']
  | HideReuseToken['type']
  | IdentifierToken['type']
  | IfToken['type']
  | ImageToken['type']
  | IndexerToken['type']
  | InputNumberToken['type']
  | InputTextToken['type']
  | LabelToken['type']
  | LineBreakToken['type']
  | LinkToken['type']
  | LogicalOperatorToken['type']
  | MultiReplaceElseToken['type']
  | NumberLiteralToken['type']
  | OpenMultiReplaceToken['type']
  | OpenParenthesisToken['type']
  | OpenPrintCapitaliseAllToken['type']
  | OpenPrintCapitaliseFirstToken['type']
  | OpenPrintToken['type']
  | OpenSquareBracketToken['type']
  | PageBreakToken['type']
  | ParametersToken['type']
  | ProseToken['type']
  | RestoreCheckpointToken['type']
  | ReturnToken['type']
  | SaveCheckpointToken['type']
  | SceneEndToken['type']
  | SceneListToken['type']
  | SceneStartToken['type']
  | SelectableIfToken['type']
  | SetVariableToken['type']
  | StatChartToken['type']
  | StringLiteralToken['type']
  | UnaryOperatorToken['type'];

/**
 * Manual fallback union of all token type literals.
 * This is provided as a reference and for use with older TypeScript versions.
 */
export type TokenTypeLiteral =
  | 'Achievement'
  | 'Achieve'
  | 'AllowReuse'
  | 'AssignmentOperator'
  | 'Author'
  | 'BooleanLiteral'
  | 'CheckAchievements'
  | 'ChoiceOption'
  | 'Choice'
  | 'CloseBrace'
  | 'CloseParenthesis'
  | 'CloseSquareBracket'
  | 'Comment'
  | 'EqualityOperator'
  | 'CreateArray'
  | 'CreateTempArray'
  | 'CreateTempVariable'
  | 'CreateVariable'
  | 'DeleteArray'
  | 'DeleteVariable'
  | 'DisableReuse'
  | 'Dollar'
  | 'ElseIf'
  | 'Else'
  | 'Ending'
  | 'FakeChoice'
  | 'Finish'
  | 'GameIdentifier'
  | 'GenerateRandom'
  | 'GoSubScene'
  | 'GoSub'
  | 'GotoLabel'
  | 'GotoRandomScene'
  | 'GotoScene'
  | 'HideReuse'
  | 'Identifier'
  | 'If'
  | 'Image'
  | 'Indexer'
  | 'InputNumber'
  | 'InputText'
  | 'Label'
  | 'LineBreak'
  | 'Link'
  | 'LogicalAnd'
  | 'MultiReplaceElse'
  | 'NumberLiteral'
  | 'OpenMultiReplace'
  | 'OpenParenthesis'
  | 'OpenPrintCapitaliseAll'
  | 'OpenPrintCapitaliseFirst'
  | 'OpenPrint'
  | 'OpenSquareBracket'
  | 'PageBreak'
  | 'Parameters'
  | 'Prose'
  | 'RestoreCheckpoint'
  | 'Return'
  | 'SaveCheckpoint'
  | 'SceneEnd'
  | 'SceneList'
  | 'SceneStart'
  | 'SelectableIf'
  | 'SetVariable'
  | 'StatChart'
  | 'StringLiteral'
  | 'NotOperator';
